version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm cover
            - run: npm upload-cover
workflows:
    build-and-test:
      jobs:
        - build-and-test